In [209]:
import numpy as np
import pandas as pd

In [210]:
def hit(dc):
    roll = np.random.randint(1,21)
    if roll >= 20:
        return True
    if roll >= dc:
        return True
    return False

def advantage_hit(dc):
    roll = max(np.random.randint(1,21,2))
    if roll >= 20:
        return True
    if roll >= dc:
        return True
    return False

In [211]:
def differential(dc, damage):
    _hit = hit(dc)
    p_hit = hit(dc+5)
    
    if _hit:
        d = damage
    else:
        d = 0
    
    if p_hit:
        pd = damage + 10
    else:
        pd = 0
    
    return pd - d

def adv_differential(dc, damage):
    _hit = advantage_hit(dc)
    p_hit = advantage_hit(dc + 5)
    
    if _hit:
        d = damage
    else:
        d = 0
    
    if p_hit:
        pd = damage+10
    else:
        pd = 0
    
    return pd - d

In [212]:
def monty_diff(dc, damage, ntimes):
    return sum(differential(dc, damage) for _ in range(ntimes)) / ntimes

def monty_a_diff(dc, damage, ntimes):
    return sum(adv_differential(dc, damage) for _ in range(ntimes)) / ntimes

In [220]:
d_a = [[monty_diff(dc, dam+.5, 20000) for dc in range(5,21)] for dam in range(5, 12)]

In [221]:
d_aa = [[monty_a_diff(dc, dam+.5, 20000) for dc in range(5,21)] for dam in range(5, 12)]

In [224]:
df = pd.DataFrame(d_a, index=[dam+.5 for dam in range(5, 12)], columns=range(5,21))

In [225]:
dfa = pd.DataFrame(d_aa, index=[dam+.5 for dam in range(5,12)], columns=range(5,21))

In [226]:
df

,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
5.5,4.136150,3.607475,3.173500,2.564675,2.100025,1.657750,1.109350,0.671525,0.091725,-0.428000,-0.847725,-0.589700,-0.264975,-0.067450,0.208025,0.480725
6.5,3.934000,3.388525,2.785425,2.389100,1.905525,1.264900,0.922575,0.481725,-0.129000,-0.607300,-1.164425,-0.801100,-0.474975,-0.140425,0.190850,0.485800
7.5,3.654625,2.990250,2.652750,2.169250,1.610500,1.109750,0.563875,0.131375,-0.376375,-1.027875,-1.442250,-1.030000,-0.633750,-0.270500,0.128625,0.521500
8.5,3.459375,2.764900,2.402450,1.815475,1.391675,0.872575,0.416550,-0.219175,-0.655950,-1.052325,-1.639700,-1.267675,-0.802300,-0.354650,0.063425,0.464025
9.5,3.046975,2.660200,2.062525,1.702225,1.130900,0.685150,0.048900,-0.348575,-0.916175,-1.389425,-1.878175,-1.377000,-0.930850,-0.454500,0.042650,0.492075
10.5,2.962125,2.273700,1.876600,1.443750,0.775150,0.333375,-0.053450,-0.649750,-1.006100,-1.639375,-2.177000,-1.653825,-1.018350,-0.504025,-0.033300,0.492850
11.5,2.617125,2.150475,1.616475,1.198550,0.774300,0.262125,-0.394300,-0.930950,-1.413225,-1.880200,-2.389400,-1.801850,-1.184825,-0.656925,-0.041425,0.474750

In [227]:
dfa

,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
5.5,7.045600,6.487900,5.801100,5.073925,4.328350,3.601350,2.644375,1.770875,0.736275,-0.267275,-1.240450,-0.882525,-0.464000,-0.044775,0.434375,0.989850
6.5,6.903225,6.212725,5.553825,4.814325,4.051250,3.198350,2.391825,1.459225,0.413875,-0.578300,-1.647100,-1.267175,-0.658925,-0.173400,0.375250,0.979375
7.5,6.783750,6.042000,5.496375,4.557000,3.816500,3.070375,2.061250,1.096125,0.042750,-1.067750,-2.099125,-1.503250,-1.007250,-0.352125,0.234750,1.010125
8.5,6.592675,5.819075,5.192350,4.358375,3.443150,2.734750,1.667875,0.634225,-0.412850,-1.360775,-2.581125,-1.822375,-1.238425,-0.547400,0.107150,0.923050
9.5,6.462750,5.725050,4.916600,4.161300,3.229000,2.422075,1.376600,0.387950,-0.715975,-1.743600,-2.855550,-2.266800,-1.472700,-0.654875,-0.013675,0.956350
10.5,6.128225,5.594925,4.703875,3.905675,3.018925,2.116550,1.147175,-0.012525,-1.054300,-2.138000,-3.337350,-2.581350,-1.722700,-0.951150,-0.013125,1.038475
11.5,6.119125,5.270275,4.466325,3.609750,2.780975,1.892650,0.722475,-0.207925,-1.561625,-2.654725,-3.639900,-2.968700,-1.971125,-1.077275,0.007175,0.921450